CREATE DATABASE IF NOT EXISTS tgi_database;
USE tgi_database;

-- ==========================================
-- TABELAS DO CHÃO DE FÁBRICA (CLP / OT)
-- ==========================================

CREATE TABLE CLP_CEQP (
    MAQUINA SMALLINT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    TOPLEITURA VARCHAR(50),
    TOPENVIO VARCHAR(50),
    ATIVO CHAR(1),
    PRIMARY KEY (MAQUINA)
);

CREATE TABLE CLP_MACOMP (
    SEQ_TAREFA INT NOT NULL,
    MAQUINA SMALLINT NOT NULL,
    IDJOB VARCHAR(50),
    VELMEDCURTA DOUBLE,
    VELMEDGLOBAL DOUBLE,
    VELATUAL DOUBLE,
    CICLOMED DOUBLE,
    CICLOATUAL DOUBLE,
    QTDSETUP DOUBLE,
    QTDLIQ DOUBLE,
    QTDBRUTA DOUBLE,
    QTDREFUGO DOUBLE,
    TMPEXEC DOUBLE,
    TMPPREP DOUBLE,
    TMPBONS DOUBLE,
    TMPPARADO DOUBLE,
    TMPTOTAL DOUBLE,
    TMPREST DOUBLE,
    MAQATIVA CHAR(1),
    BTNCONTAGEM CHAR(1),
    OEEDISP DOUBLE,
    OEEDESEMP DOUBLE,
    OEEQUALID DOUBLE,
    OEETOTAL DOUBLE,
    PRIMARY KEY (SEQ_TAREFA)
);

CREATE TABLE CLP_MACOMPH (
    CODSTR VARCHAR(20) NOT NULL,
    IDMSGMQTT VARCHAR(50),
    SEQ_TAREFA INT NOT NULL,
    MAQUINA SMALLINT NOT NULL,
    IDJOB VARCHAR(50),
    VELMEDCURTA DOUBLE,
    VELMEDGLOBAL DOUBLE,
    VELATUAL DOUBLE,
    CICLOMED DOUBLE,
    CICLOATUAL DOUBLE,
    QTDSETUP DOUBLE,
    QTDLIQ DOUBLE,
    QTDBRUTA DOUBLE,
    QTDREFUGO DOUBLE,
    TMPEXEC DOUBLE,
    TMPPREP DOUBLE,
    TMPBONS DOUBLE,
    TMPPARADO DOUBLE,
    TMPTOTAL DOUBLE,
    TMPREST DOUBLE,
    MAQATIVA CHAR(1),
    BTNCONTAGEM CHAR(1),
    OEEDISP DOUBLE,
    OEEDESEMP DOUBLE,
    OEEQUALID DOUBLE,
    OEETOTAL DOUBLE,
    PRIMARY KEY (SEQ_TAREFA, CODSTR)
);

CREATE TABLE CLP_MLOG (
    CODSTR VARCHAR(20) NOT NULL,
    DTI DATETIME,
    USUDB VARCHAR(30),
    TPLOG SMALLINT,
    TPLOGSTR VARCHAR(20),
    TABELA VARCHAR(20),
    PROCESSO VARCHAR(60),
    DESCRICAO VARCHAR(250),
    CODINT1 INT,
    CODINT2 INT,
    CODINT3 INT,
    CODINT4 INT,
    CODINT5 INT,
    CODSTR1 VARCHAR(20),
    OBSLOG TEXT
);
CREATE INDEX CLP_MLOG_CODSTR ON CLP_MLOG (CODSTR);
CREATE INDEX CLP_MLOG_TPLOGTABELA ON CLP_MLOG (TPLOG, TABELA);

CREATE TABLE CLP_MMSGENV (
    CODSTR VARCHAR(20) NOT NULL,
    SEQ_TAREFA INT NOT NULL,
    MAQUINA SMALLINT NOT NULL,
    IDJOB VARCHAR(50),
    DTI DATETIME,
    DTPROGENV DATETIME,
    JAENVIOU CHAR(1) NOT NULL,
    DTENVIO DATETIME,
    EXCLUIR CHAR(1) NOT NULL,
    TOPICOFNL VARCHAR(50),
    TOPICOCPL VARCHAR(250),
    USUDB VARCHAR(30)
);
CREATE INDEX CLP_MMSGENV_CODSTR ON CLP_MMSGENV (CODSTR);
CREATE INDEX CLP_MMSGENV_JAENVIOU ON CLP_MMSGENV (JAENVIOU);
CREATE INDEX CLP_MMSGENV_EXCLUIR ON CLP_MMSGENV (EXCLUIR);

CREATE TABLE CLP_MMSGENVT (
    CODSTR VARCHAR(20) NOT NULL,
    IDMSGMQTT VARCHAR(50),
    MEMJS TEXT
);
CREATE INDEX CLP_MMSGENVT_CODSTR ON CLP_MMSGENVT (CODSTR);

CREATE TABLE CLP_MMSGHIST (
    TABORIG VARCHAR(30) NOT NULL,
    CODSTR VARCHAR(20) NOT NULL,
    DTI DATETIME,
    JALEU CHAR(1) NOT NULL,
    DTLEITURA DATETIME,
    EXCLUIR CHAR(1) NOT NULL,
    TOPICOFNL VARCHAR(50),
    TOPICOCPL VARCHAR(250),
    USUDB VARCHAR(30),
    IDMSGMQTT VARCHAR(50) NOT NULL,
    MEMJS TEXT
);
CREATE INDEX CLP_MMSGHIST_TABORIGCODSTR ON CLP_MMSGHIST (TABORIG, CODSTR);

CREATE TABLE CLP_MMSGREC (
    CODSTR VARCHAR(20) NOT NULL,
    SEQ_TAREFA INT NOT NULL,
    MAQUINA SMALLINT NOT NULL,
    IDJOB VARCHAR(50),
    DTI DATETIME,
    JALEU CHAR(1) NOT NULL,
    DTLEITURA DATETIME,
    EXCLUIR CHAR(1) NOT NULL,
    TOPICOFNL VARCHAR(50),
    TOPICOCPL VARCHAR(250),
    USUDB VARCHAR(30)
);
CREATE INDEX CLP_MMSGREC_CODSTR ON CLP_MMSGREC (CODSTR);
CREATE INDEX CLP_MMSGREC_JALEU ON CLP_MMSGREC (JALEU);
CREATE INDEX CLP_MMSGREC_EXCLUIR ON CLP_MMSGREC (EXCLUIR);

CREATE TABLE CLP_MMSGRECL (
    CODSTR VARCHAR(20) NOT NULL,
    SEQ_TAREFA INT NOT NULL,
    MAQUINA SMALLINT NOT NULL,
    DTLEITURA DATETIME
);

CREATE TABLE CLP_MMSGRECT (
    CODSTR VARCHAR(20) NOT NULL,
    IDMSGMQTT VARCHAR(50) NOT NULL,
    MEMJS TEXT
);
CREATE INDEX CLP_MMSGRECT_CODSTR ON CLP_MMSGRECT (CODSTR);

CREATE TABLE CLP_MSEMAF (
    QUEMINI VARCHAR(50) NOT NULL,
    DTINI DATETIME NOT NULL,
    DTFIM DATETIME,
    TMPSEMAF DOUBLE,
    DIRINIC VARCHAR(200),
    INTRDM INT
);
CREATE INDEX CLP_MSEMAF_DTINIDTFIM ON CLP_MSEMAF (DTINI, DTFIM);

-- ==========================================
-- TABELAS DO SISTEMA ERP (TI)
-- ==========================================

CREATE TABLE AG_MOCOR (
    SEQ_TAREFA INT NOT NULL,
    SEQ_OCORRE SMALLINT NOT NULL,
    INICIO DATETIME,
    FIM DATETIME,
    CODTPTAR SMALLINT,
    CODTPOCOR SMALLINT,
    OPERADOR SMALLINT,
    CODORIGEM CHAR(1) DEFAULT '1',
    QTDPERDA DOUBLE,
    QTDPERDACONV DOUBLE,
    UNI CHAR(3),
    TURNO CHAR(1),
    TERMINAL SMALLINT,
    IDAPONT VARCHAR(10),
    JUSTIFICA TEXT,
    CODOPERJUST SMALLINT,
    OPERADORF SMALLINT,
    TSCODAPON INT,
    TSIDENTAPON VARCHAR(30),
    CALCTMPDIAS DOUBLE,
    CALCTMPHOR DOUBLE,
    CALCTMPMIN DOUBLE,
    OPERADORI SMALLINT,
    IGNORBXAVIN SMALLINT,
    DTI DATETIME,
    DTA DATETIME,
    USUI SMALLINT,
    USUA SMALLINT,
    PRIMARY KEY (SEQ_TAREFA, SEQ_OCORRE)
);

CREATE TABLE AG_MTAR (
    SEQ_TAREFA INT NOT NULL,
    CODTPTAR SMALLINT,
    MAQUINA SMALLINT,
    ESTADO CHAR(1),
    PRIORIDADE CHAR(1),
    INIPRJINI DATETIME,
    INIPREV DATETIME,
    INIPROG DATETIME,
    INIREAL DATETIME,
    FIMPRJINI DATETIME,
    FIMPREV DATETIME,
    FIMPROG DATETIME,
    FIMREAL DATETIME,
    TIPOPRG CHAR(1) DEFAULT '0' NOT NULL,
    NEW_TAREFA INT,
    PPREVPERDAC DOUBLE,
    PPREVPERDAO DOUBLE,
    PPREVPERAC DOUBLE,
    QTDPREV DOUBLE,
    QTDPREVO DOUBLE,
    QTDPERDA DOUBLE,
    QTDPERDAO DOUBLE,
    QTDPERDAACE DOUBLE,
    QTDPERDAACEO DOUBLE,
    QTDREAL DOUBLE,
    QTDPREVACE SMALLINT DEFAULT 1,
    VELOCIDC DOUBLE,
    VELOCIDO DOUBLE,
    PERVELOC DOUBLE,
    UNI CHAR(1),
    UNIEST CHAR(1),
    UNIENT CHAR(1),
    CONVUNIEST DOUBLE,
    CONVUNIENT DOUBLE,
    TMPPREPCALC INT,
    TMPPREPOPER INT,
    TMPPROCALC INT,
    TMPPROOPER INT,
    QTDRODA SMALLINT,
    PULSOS INT DEFAULT 0 NOT NULL,
    DIVIDERODA SMALLINT DEFAULT 1,
    CODFORN INT,
    TMPDESCCALC SMALLINT,
    TMPDESCOPER SMALLINT,
    INIPREVDESC DATETIME,
    FIMPREVDESC DATETIME,
    INIREALDESC DATETIME,
    FIMREALDESC DATETIME,
    DTLIBDESC DATETIME,
    USULIBDESC SMALLINT,
    OPERLIBDESC SMALLINT,
    JUSTLIBDESC TEXT,
    OBSTAR TEXT,
    OPCODSEQPR INT,
    RETRABALHO CHAR(1),
    CONGELAR CHAR(1),
    DTCONGELOU DATETIME,
    USUCONGELOU SMALLINT,
    DTDESCONG DATETIME,
    USUDESCONG SMALLINT,
    FLSEQTARANT INT,
    QTDPREVORC DOUBLE,
    QTDPERDAORC DOUBLE,
    TMPPREPCALCORC INT,
    TMPPROCALCORC INT,
    CUSTOINC DOUBLE,
    CUSTOINI DOUBLE,
    CUSTOFIM DOUBLE,
    ENTRADAMAQ SMALLINT,
    CODTPPROC SMALLINT,
    SEQREGRA SMALLINT,
    REGRAINFO CHAR(1),
    QTDINFO1 DOUBLE,
    QTDINFO2 DOUBLE,
    QTDINFO3 DOUBLE,
    CODMP SMALLINT,
    FATORMP DOUBLE,
    VALOROPC SMALLINT,
    PREINIPROG DATETIME,
    PREFIMPROG DATETIME,
    TARAPLICREF CHAR(1),
    INFREFAPLIC TEXT,
    QTDCALCKGB DOUBLE,
    QTDCALCKGL DOUBLE,
    GRAMASMQ DOUBLE,
    PRIMPROGPARA DATETIME,
    DTI DATETIME,
    DTA DATETIME,
    USUI SMALLINT,
    USUA SMALLINT,
    PRIMARY KEY (SEQ_TAREFA)
);
CREATE INDEX AG_MTAR_MAQUINAFIMREAL ON AG_MTAR (MAQUINA, FIMREAL);
CREATE INDEX AG_MTAR_ESTADO ON AG_MTAR (ESTADO);
CREATE INDEX AG_MTAR_INIPROG ON AG_MTAR (INIPROG);

CREATE TABLE AG_MTARC (
    EMPRESA SMALLINT NOT NULL,
    NUMPED INT NOT NULL,
    NUMITEM SMALLINT NOT NULL,
    NUMTIRAG SMALLINT NOT NULL,
    NUMCOMPON SMALLINT NOT NULL,
    SEQ_TAREFA INT NOT NULL,
    OPSEQOPER SMALLINT,
    OPSEQORDEM SMALLINT,
    ORDEM SMALLINT,
    DESCRICAO VARCHAR(100),
    NUMMONTAG SMALLINT,
    PERCMONTAG SMALLINT,
    LAMINASTAR SMALLINT,
    CARGA DOUBLE,
    NCORF SMALLINT,
    NCORV SMALLINT,
    NVERF SMALLINT,
    NVERV SMALLINT,
    ORCODORC INT,
    ORSEQVER SMALLINT,
    ORNUMCOMP SMALLINT,
    ORSEQMTG SMALLINT,
    ORSEQPROC SMALLINT,
    ORSEQTAR SMALLINT,
    VINCCOMP VARCHAR(90),
    DTI DATETIME,
    DTA DATETIME,
    USUI SMALLINT,
    USUA SMALLINT,
    PRIMARY KEY (EMPRESA, NUMPED, NUMITEM, NUMTIRAG, NUMCOMPON, SEQ_TAREFA),
    CONSTRAINT FK_AG_MTARC_SEQ_TAREFA FOREIGN KEY (SEQ_TAREFA) REFERENCES AG_MTAR (SEQ_TAREFA)
);
CREATE INDEX AG_MTARC_EMPRESANUMPEDNUMITEMN ON AG_MTARC (EMPRESA, NUMPED, NUMITEM, NUMTIRAG, NUMCOMPON);
CREATE INDEX AG_MTARC_EMPPEDITEMTIRAG ON AG_MTARC (EMPRESA, NUMPED, NUMITEM, NUMTIRAG);

-- OBS: As chaves estrangeiras de AG_CTAR, AG_CEQP, FV_FAVOR e AG_MOS 
-- não foram criadas aqui para evitar erros, pois as tabelas originais 
-- não estavam no documento base.